version: "3.9"

networks:
  stadium-network-proxy:
    external: true


services:
  frontend:
    container_name: ${CONTAINER_CODE_NAME}
    build:
      context: ../../
      dockerfile: ops/docker/Dockerfile
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ../../:/app
      - sthp-node_modules:/app/node_modules
    ports:
      - "${APP_PORT:-3000}:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-${CONTAINER_CODE_NAME}.rule=Host(`panel.stadium-hub.loc`)"
      - "traefik.docker.network=stadium-network-proxy"
    networks:
      stadium-network-proxy:


volumes:
  sthp-node_modules: